CREATE TABLE user (
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
gender ENUM('M', 'F') NOT NULL,
email VARCHAR(255) NOT NULL,
user_password VARCHAR(255) NOT NULL,
date_of_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post (
id INT PRIMARY KEY AUTO_INCREMENT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
title VARCHAR(255) NOT NULL,
content VARCHAR(255) NOT NULL,
created_by INT,
FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE comment (
id INT PRIMARY KEY AUTO_INCREMENT,
post_id INT,
user_id INT,
content VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE `like` (
id INT PRIMARY KEY AUTO_INCREMENT,
post_id INT,
user_id INT,
FOREIGN KEY (Post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (User_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);