SET ENGINE = InnoDB;

CREATE TABLE user (
id INT PRIMARY KEY AUTO_INCREMENT,
user INT,
username VARCHAR(255) NOT NULL,
gender ENUM('Male', 'Female') NOT NULL,
email VARCHAR(255) NOT NULL,
user_password VARCHAR(255) NOT NULL,
date_of_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT user_mail UNIQUE (username, email),
FOREIGN KEY (user) REFERENCES user_info(id) ON DELETE CASCADE ON UPDATE CASCADE;
);

CREATE TABLE user_info (
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);

CREATE TABLE post (
id INT PRIMARY KEY AUTO_INCREMENT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
title INT,
content TEXT NOT NULL,
created_by INT,
FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE post_title (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title_name VARCHAR(255) NOT NULL,
    FOREIGN KEY (id) REFERENCES post(title);
)


CREATE TABLE comment (
id INT PRIMARY KEY AUTO_INCREMENT,
post_id INT,
user_id INT,
content VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE `like` (
id INT PRIMARY KEY AUTO_INCREMENT,
post_id INT,
user_id INT,
FOREIGN KEY (Post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (User_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);